-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 18:16:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shego
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shego
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shego` DEFAULT CHARACTER SET utf8 ;
USE `shego` ;

-- -----------------------------------------------------
-- Table `shego`.`fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`fornecedores` ;

CREATE TABLE IF NOT EXISTS `shego`.`fornecedores` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nomeFornecedor` VARCHAR(200) NOT NULL,
  `telefoneFornecedor` VARCHAR(20) NULL,
  `emailFornecedor` VARCHAR(200) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `nomeFornecedor_UNIQUE` (`nomeFornecedor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`produtos` ;

CREATE TABLE IF NOT EXISTS `shego`.`produtos` (
  `idProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `idFornecedor` INT(11) NOT NULL,
  `eanProduto` VARCHAR(12) NOT NULL,
  `nomeProduto` VARCHAR(200) NOT NULL,
  `qtdProduto` INT(11) NOT NULL,
  `valorCompraProduto` FLOAT NOT NULL,
  `valorVendaProduto` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `eanProduto_UNIQUE` (`eanProduto` ASC),
  INDEX `fk_produtos_1_idx` (`idFornecedor` ASC),
  CONSTRAINT `idFornecedor`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `shego`.`fornecedores` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`clientes` ;

CREATE TABLE IF NOT EXISTS `shego`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(200) NOT NULL,
  `telefoneCliente` VARCHAR(20) NOT NULL,
  `emailCliente` VARCHAR(200) NULL,
  `enderecoCliente` VARCHAR(200) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`despesas` ;

CREATE TABLE IF NOT EXISTS `shego`.`despesas` (
  `idDespesa` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeDespesa` VARCHAR(200) NOT NULL,
  `valorDespesa` FLOAT NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `dataPagamento` DATE NULL,
  `status` BOOLEAN DEFAULT 0,
  PRIMARY KEY (`idDespesa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `shego`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(200) NOT NULL,
  `loginUsuario` VARCHAR(200) NOT NULL,
  `senhaUsuario` VARCHAR(200) NOT NULL,
  `cargoUsuario` VARCHAR(200) NOT NULL DEFAULT 'ADMINISTRADOR',
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO usuarios VALUES (null,'admin','admin','admin','ADMINISTRADOR');

-- -----------------------------------------------------
-- Table `shego`.`dinheiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`dinheiro` ;

CREATE TABLE IF NOT EXISTS `shego`.`dinheiro` (
  `iddinheiro` INT NOT NULL,
  `total` FLOAT(10,2) NOT NULL,
  `pago` FLOAT(10,2) NOT NULL,
  `status` INT NOT NULL,
  `conclusao` DATE NULL,
  PRIMARY KEY (`iddinheiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shego`.`cheque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`cheque` ;

CREATE TABLE IF NOT EXISTS `shego`.`cheque` (
  `idcheque` INT NOT NULL,
  `total` FLOAT(10,2) NOT NULL,
  `data` DATE NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`idcheque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shego`.`cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`cartao` ;

CREATE TABLE IF NOT EXISTS `shego`.`cartao` (
  `idcartao` INT NOT NULL,
  `total` FLOAT(10,2) NULL,
  `data` DATE NULL,
  `status` INT NULL,
  PRIMARY KEY (`idcartao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shego`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shego`.`venda` ;

CREATE TABLE IF NOT EXISTS `shego`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `clientes_idClientes` INT NOT NULL,
  `produtos_idProduto` INT(11) NOT NULL,
  `qtd` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `id_tipo` INT NOT NULL,
  `date` DATE NULL,
  `total` FLOAT(10,2) NULL,
  PRIMARY KEY (`idvenda`, `clientes_idClientes`, `produtos_idProduto`),
  INDEX `fk_venda_clientes1_idx` (`clientes_idClientes` ASC),
  INDEX `fk_venda_produtos1_idx` (`produtos_idProduto` ASC),
  CONSTRAINT `fk_venda_clientes1`
    FOREIGN KEY (`clientes_idClientes`)
    REFERENCES `shego`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produtos1`
    FOREIGN KEY (`produtos_idProduto`)
    REFERENCES `shego`.`produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
