-- MySQL Script generated by MySQL Workbench
-- seg 08 out 2018 22:33:26 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shego
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shego
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shego` DEFAULT CHARACTER SET utf8 ;
USE `shego` ;

-- -----------------------------------------------------
-- Table `shego`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shego`.`fornecedores` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nomeFornecedor` VARCHAR(200) NOT NULL,
  `telefoneFornecedor` VARCHAR(20) NULL,
  `emailFornecedor` VARCHAR(200) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `nomeFornecedor_UNIQUE` (`nomeFornecedor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shego`.`produtos` (
  `idProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `idFornecedor` INT(11) NOT NULL,
  `eanProduto` VARCHAR(12) NOT NULL,
  `nomeProduto` VARCHAR(200) NOT NULL,
  `qtdProduto` INT(11) NOT NULL,
  `valorCompraProduto` FLOAT NOT NULL,
  `valoVendaProduto` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `eanProduto_UNIQUE` (`eanProduto` ASC),
  INDEX `fk_produtos_1_idx` (`idFornecedor` ASC),
  CONSTRAINT `idFornecedor`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `shego`.`fornecedores` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shego`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(200) NOT NULL,
  `telefoneCliente` VARCHAR(20) NOT NULL,
  `emailCliente` VARCHAR(200) NULL,
  `enderecoCliente` VARCHAR(200) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`clientes_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shego`.`clientes_has_produtos` (
  `clientes_idClientes` INT NOT NULL,
  `produtos_idProduto` INT(11) NOT NULL,
  PRIMARY KEY (`clientes_idClientes`, `produtos_idProduto`),
  INDEX `fk_clientes_has_produtos_produtos1_idx` (`produtos_idProduto` ASC),
  INDEX `fk_clientes_has_produtos_clientes1_idx` (`clientes_idClientes` ASC),
  CONSTRAINT `fk_clientes_has_produtos_clientes1`
    FOREIGN KEY (`clientes_idClientes`)
    REFERENCES `shego`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_produtos_produtos1`
    FOREIGN KEY (`produtos_idProduto`)
    REFERENCES `shego`.`produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shego`.`despesas` (
  `idDespesa` INT(11) NOT NULL,
  `nomeDespesa` VARCHAR(200) NOT NULL,
  `valorDespesa` FLOAT NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `dataPagamento` DATE NULL,
  PRIMARY KEY (`idDespesa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shego`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shego`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(200) NOT NULL,
  `loginUsuario` VARCHAR(200) NOT NULL,
  `senhaUsuario` VARCHAR(200) NOT NULL,
  `cargoUsuario` VARCHAR(200) NOT NULL DEFAULT 'ADMINISTRADOR',
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO usuarios VALUES (null,'Administrador','admin','admin','ADMINISTRADOR');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
